spring.mongodb.database=invoice-platform-test

security.admin.username=admin
security.admin.password=admin-password

security.jwt.secret=fN9+pGtliYZEfk7xXl5+rXMIX67OTtlLVTrI4tw9Y28=
security.jwt.expiration=1h